version: '3.3'

services:
  sonar-scanner:
    build: ./dockerfiles/sonar-scanner/.
    volumes:
      - "./src:/var/www/html"
    networks:
      - docker-sonar-scanner
    entrypoint: sonar-scanner

networks:
  docker-sonar-scanner:
    driver: 'bridge'
